// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD34Kd6n3kaYgXLBq7Ec4TnLWkaBGfNM8g',
    appId: '1:10559117739:web:a29180a0d7efb42da45aee',
    messagingSenderId: '10559117739',
    projectId: 'spacebook-e1ed3',
    authDomain: 'spacebook-e1ed3.firebaseapp.com',
    storageBucket: 'spacebook-e1ed3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVFeYac6uztK_No7yuN_pujWVmyn3Ke58',
    appId: '1:10559117739:android:542bc2daa8d1df08a45aee',
    messagingSenderId: '10559117739',
    projectId: 'spacebook-e1ed3',
    storageBucket: 'spacebook-e1ed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdjqHchD8MjRhXaE0YebN3yM5OZ7WKGnE',
    appId: '1:10559117739:ios:31398f808f13cc44a45aee',
    messagingSenderId: '10559117739',
    projectId: 'spacebook-e1ed3',
    storageBucket: 'spacebook-e1ed3.firebasestorage.app',
    iosClientId: '10559117739-u0re1f37sv0qk8hc55ep74q5pdna7fas.apps.googleusercontent.com',
    iosBundleId: 'com.example.spacebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdjqHchD8MjRhXaE0YebN3yM5OZ7WKGnE',
    appId: '1:10559117739:ios:31398f808f13cc44a45aee',
    messagingSenderId: '10559117739',
    projectId: 'spacebook-e1ed3',
    storageBucket: 'spacebook-e1ed3.firebasestorage.app',
    iosClientId: '10559117739-u0re1f37sv0qk8hc55ep74q5pdna7fas.apps.googleusercontent.com',
    iosBundleId: 'com.example.spacebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD34Kd6n3kaYgXLBq7Ec4TnLWkaBGfNM8g',
    appId: '1:10559117739:web:6628229556db4b69a45aee',
    messagingSenderId: '10559117739',
    projectId: 'spacebook-e1ed3',
    authDomain: 'spacebook-e1ed3.firebaseapp.com',
    storageBucket: 'spacebook-e1ed3.firebasestorage.app',
  );
}
